[phases]
build = """
composer install --optimize-autoloader --no-dev
npm install --production
php artisan optimize
php artisan config:cache
php artisan route:cache
php artisan view:cache
php artisan migrate --force
"""

start = "php artisan serve --host=0.0.0.0 --port=${PORT}"
